# Generated by Django 6.0.4 on 2026-04-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='distros/')),
                ('rolling_release', models.BooleanField(default=False)),
                ('last_build_stable', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
