# Generated by Django 6.0.4 on 2026-04-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distro',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
